// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enomrurreqgskhpyskxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVub21ydXJyZXFnc2tocHlza3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMTkzNzQsImV4cCI6MjA1NTg5NTM3NH0.ZdZm2_BA8qCtbmy0lxM_2MDQLCflZtjdTFuRMFbeyCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);